---
site_name: Stock Backtest Fundamental
site_description: Documentation for the Stock Backtest Fundamental Project
site_author: Mark Quinn
repo_url: https://github.com/finsite/stock-backtest-fundamental
theme:
  name: material
nav:
  - Home: index.md
  - API Reference: api.md
  - More Details: more-details.md
  - Other Topic: other-topic.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
markdown_extensions:
  - admonition
  - toc:
      permalink: true
