---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

namespace: default

labels:
  - includeSelectors: true
    pairs:
      app: stock-backtest-fundamental

images:
  - name: stock-backtest-fundamental
    newName: stock-backtest-fundamental
    newTag: latest
